---
ID: "dc9c682b-7d3e-4bd0-8c8b-d8d554a90512"
Parent: "22a76464-a921-4232-a8ab-e192e3e8fb70"
Template: "854ba861-63ea-4a0c-8c7b-541e9a7ec4c1"
Path: /sitecore/system/Settings/Rules/Definitions/Elements/Device Detection Module/Tags/Default
DB: master
SharedFields:
- ID: "42f77151-098f-496a-94cf-590b7edeeabe"
  Hint: Tags
  Type: Multilist
  Value: "{36C2B7B6-6B46-4C41-9E78-230DA2C5EC90}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150625T084005
